### PR TITLE
Fix the macOS keyboard shortcut to paste into a terminal

### PR DESCRIPTION
**Pull request by crushedice2000**
As OS X has `cmd` and `ctrl` keys, normally there is not need to use `shift` as modifier. This means that copy would be `cmd+c` and interrupt proccess `ctrl+c`.

### CODE REVIEW

**Comment by greenbreakfast** [comment]
The issue is that the terminal app does **not** use the regular cmd+v shortcut for pasting.
So ctrl+c is interrupt process and cmd+shift+v is paste, cmd+c is copy.

Good eye tho!

**Comment by crushedice2000** [comment]
@greenbreakfast: Do you mean Terminal.app (the default terminal emulator in macOS) or the Onion Console Terminal? In Terminal.app the copy shortcut is `cmd+c` and the paste shortcut is `cmd+v`. AFAIK the document I edited does't explicitly refer to the Onion Console Terminal. 

> In order to develop programs on the command-line, you'll need access to a terminal so either SSH into the Omega's command-line, or connect serially.

Maybe I'm wrong and skipped something in the text. Maybe should we specify that the user should use (no pun intended) the Onion Console Terminal?

**Comment by greenbreakfast** [comment]
Oh man, I thought I was looking at a different article, you're absolutely right!

**Comment by greenbreakfast** [comment]
didn't merge since the file has since been changed, but included the main text manually

**Pull request closed without merging**
